version: 2

before:
  hooks:
    - go test -v ./...
    - go vet -v ./...

builds:
  - id: gitk-go
    binary: gitk-go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - gitcli

  - id: gitk-go-purego
    binary: gitk-go-purego
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [ 'tar.xz' ]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--checksums.txt"
release:
  draft: false
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
